name: safeeats
description: A food safety app for scanning products and managing dietary restrictions.
publish_to: 'none'
version: 0.0.1-alpha

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^3.4.1
  shared_preferences: ^2.2.1
  http: ^1.1.0
  path_provider: ^2.1.1
  uuid: ^4.1.0
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
